# Generated by Django 5.0.4 on 2024-04-25 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registroestudiantes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='descripción',
            new_name='descripcion',
        ),
    ]
